#+title: A better than even chance
#+date: <2023-02-10 Fri 21:44>
#+author: thebesttv

看 SICP 的时候发现的.  不算个特定的短语吧, 就是 better than + an even chance,
不过第一次看的时候还没反应过来hh

#+begin_quote
Thus, if $n$ passes the test for some random choice of $a$, *the chances
are better than even* that $n$ is prime.  If $n$ passes the test for two
random choices of $a$, the chances are better than 3 out of 4 that $n$
is prime.  By running the test with more and more randomly chosen values
of $a$ we can make the probability of error as small as we like.

---Section 1.2.6 /Example: Testing for Primality/;
subsection /Probabilistic methods/
#+end_quote

挺有意思的说法: *the chances are better than even*.

主要就是 an even chance 是啥意思: an equally balanced probability (两两开).
当然, 除了 even chance, 还有 even probability/likelihood
- I'd say he has an even chance of winning the match.
- There was always better than an even chance of something like this
  happening.
- In a Duel they have an even chance for their lives.
- We have seen that there is at least an even likelihood that the babe
  was a boy.

一些个例句:
- Webster 对 odds-on 的第一个解释:
  having or viewed as having a better than even chance to win.
  E.g. the odds-on favorite
- There exists an invention that seems to have a better than even chance
  of rendering 40,000,000 radio sets obsolete and of upsetting the
  status quo of the broadcasting industry.
- Most expatriate (侨民) employees have a better than even probability
  of getting their hands on the steering wheel of a company car.
