name: Build & cache Emacs Docker image

on:
  workflow_dispatch:

jobs:
  Build-and-cache-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Build image
        runs: |
          cd docker/
          docker build -t emacs --build-arg UNAME=$(whoami) --build-arg UID=$(id -u) --build-arg GID=$(id -g) .
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
