name: Publish to GitHub Pages

on:
  schedule:
    - cron: '33 18 * * *'       # UTC 18:33 => UTC+8 2:33
  push:
    branches:
      - '*'                     # run on all branches
  workflow_dispatch:

jobs:
  Generate-target:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: |
          sudo mkdir /emacs
          sudo chown $USER: /emacs
      - name: Cache Emacs installation
        id: cache-emacs-installation
        uses: actions/cache@v3
        with:
          path: |
            /emacs
          key: ${{ runner.os }}-emacs-installation
      - name: Cache Emacs package
        id: cache-emacs-package
        uses: actions/cache@v3
        with:
          path: |
            ~/.emacs
            ~/.emacs.d
          key: ${{ runner.os }}-emacs-package
      - name: Install Emacs
        if: steps.cache-emacs-installation.outputs.cache-hit != 'true'
        env:
          name: emacs-28.2
        run: |
          sudo sed -i 's/^# deb-src/deb-src/' /etc/apt/sources.list
          >/dev/null sudo apt-get update
          >/dev/null sudo apt-get -y install build-essential
          >/dev/null sudo apt-get -y build-dep emacs
          wget -q https://ftp.gnu.org/gnu/emacs/${{ env.name }}.tar.xz
          tar xf ${{ env.name }}.tar.xz
          cd ${{ env.name }}
          mkdir build && cd build
          ../configure --prefix=/emacs --with-x-toolkit=no --with-jpeg=no --with-png=no --with-gif=no --with-tiff=no
          >/dev/null make
          >/dev/null make install

          # save Emacs libs
          mkdir /emacs/cached-libs
          cp $(ldd /emacs/bin/${{ env.name }} | grep '=> /lib/' | cut -d' ' -f 3) /emacs/cached-libs
      - name: Prepare Emacs
        run: |
          # restore Emacs libs
          sudo cp /emacs/cached-libs/* /lib/x86_64-linux-gnu/
          echo "/emacs/bin" >> $GITHUB_PATH
      - name: Test Emacs
        run: |
          emacs --version

      - name: Set time-zone to ShangHai
        run: |
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          date
          emacs -Q --batch --eval "(print (current-time-zone))"
          emacs -Q --batch --eval "(print (current-time-string))"

      - name: Checkout repo (full history)
        uses: actions/checkout@v3
        with:
          # from https://github.com/marketplace/actions/git-restore-mtime
          # git-restore-mtime uses the ref log to find the correct
          # timestamp for each file.  This requires a full git history.
          # The default value (1) creates a shallow checkout.
          fetch-depth: 0
      - name: Prepare git-restore-mtime
        env:
          url: https://raw.githubusercontent.com/MestreLion/git-tools/main/git-restore-mtime
          bin: /bin/git-restore-mtime
        run: |
          sudo wget -q ${{ env.url }} -o ${{ env.bin }}
          sudo chmod +x ${{ env.bin }}
      - name: Restore mtime
        run: |
          git restore-mtime
          ls -alhF
          ls -alhF blog

      - name: Generate Diagram
        uses: githubocto/repo-visualizer@main
        with:
          output_file: "diagram.svg"
          excluded_paths: ".github,.gitignore"
          should_push: false           # do not push, instead,
          artifact_name: 'diagram-svg' # generate an artifact

      - name: Publish
        run: make publish
        env:
          ELPA_SRC: no_mirror
      - name: List current repo
        run: |
          ls -alhF

      - name: Generate pagefind
        run: make pagefind

      - name: Verify target
        run: |
          pip3 install beautifulsoup4 > /dev/null
          make verify
      - name: Upload target
        uses: actions/upload-artifact@v3
        with:
          name: target-dir
          path: target

  Publish-target:
    runs-on: ubuntu-latest
    needs: Generate-target
    if: github.ref == 'refs/heads/main' # only publish when we are on main branch
    steps:
      - name: Download target
        uses: actions/download-artifact@v3
        with:
          name: target-dir
          path: target
      - name: Download diagram
        uses: actions/download-artifact@v3
        with:
          name: diagram-svg
          path: target
      - name: Remove background of diagram
        run: |
          sed -i "s/background:white;//" target/diagram.svg
      - name: Bypass Jekyll processing
        # bypass Jekyll processing, so files or directories that start
        # with underscores are allowed, see
        # https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/
        run: |
          touch target/.nojekyll

      - name: List target directory
        run: |
          ls -alhF target/
      - name: Pushes to GitHub Pages
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'target'
          destination-github-username: 'thebesttv'
          destination-repository-name: 'thebesttv.github.io'
          user-email: taojuntian@outlook.com
          target-branch: main
